spring:
  redis:
    host: www.ljq.com
    password:
    port: 6379
  main:
    allow-bean-definition-overriding: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    test:
      url: micro-client
      path: /test/**

micro:
  sign:
    secret: 41ef3d95172afab5f1a77c392a0bfcae

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true

  docker run -p 8302:8302 -v /micro:/micro --name micro-zuul micro-zuul:1.0.0 --spring.profiles.active=test