server:
  port: 8306
  tomcat:
    uri-encoding: UTF-8
    basedir: /micro/tmp

spring:
  application:
    name: micro-auth
  redis:
    url: www.ljq.com
    password:
    pool: 6379
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://192.168.1.54:3306/admin?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

micro:
  sign:
    secret: 41ef3d95172afab5f1a77c392a0bfcae