spring:
  redis:
    host: localhost
    password:
    port: 6379
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://micro-client
          predicates:
            - Path= /test/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
        - name: RequestRateLimiter
          args:
            # 令牌桶的容量
            redis-rate-limiter.replenishRate: 1
            # 流量
            redis-rate-limiter.burstCapacity: 3
            # 过滤规则
            key-resolver: "#{@remoteAddrKeyResolver}"
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
  shareSecurityContext: true